src/objects/Applicant__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>Sri Lanka</fullName>
                </value>
                <value>
                    <fullName>Pakistan</fullName>
                </value>
                <value>
                    <fullName>Nepal</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <label>Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/triggerHandler1.cls
public with sharing class triggerHandler1 {

    public Applicant__c applicantVariable;

    public triggerHandler1(ApexPages.StandardController controller) {
        applicantVariable = [SELECT Id, Name, Address__c,Country__c,Zip_Code__c FROM Applicant__c
                WHERE Id = :ApexPages.currentPage().getParameters().get('id')];
    }

    public void tryTrigger(){
        insert applicantVariable;
    }

    public static boolean checkValue(Applicant__c applicantObject){
        Boolean value;
        if(applicantObject.Name == Null) {
         value=true;
         }
        return value;
    }
   
}