src/objects/Applicant__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>Sri Lanka</fullName>
                </value>
                <value>
                    <fullName>Pakistan</fullName>
                </value>
                <value>
                    <fullName>Nepal</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <label>Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pro__c.object
<CustomObject>
    <fields>
        <fullName>phone__c</fullName>
        <label>phone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>problem__c</fullName>
        <label>problem</label>
        <referenceTo>problem__c</referenceTo>
        <relationshipLabel>pros</relationshipLabel>
        <relationshipName>pros</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>pro</label>
    <nameField>
        <label>pro Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>pros</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/problem__c.object
<CustomObject>
    <label>problem</label>
    <nameField>
        <label>problem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>problems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/checkUpsertTrigger.cls
public with sharing class checkUpsertTrigger {

    private final List<Applicant__c> applicantVarible;
    private pro__c proVariable,temp;
    private problem__c problemVariable;

    public checkUpsertTrigger() {
      /* ID sampleId = 'a0V2v00000VpBWZEA3' ;
        applicantVarible = [SELECT Id, Name, Address__c,Country__c,Zip_Code__c FROM Applicant__c
        WHERE Id = : sampleId];
         for(Applicant__c appIterate : applicantVarible){
             appIterate.Zip_Code__c ='600025';
             
         }
        applicantVarible.add(new Applicant__c(Name='Viji'));
        
        upsert applicantVarible;
        System.debug(applicantVarible);*/
    }

    
    public void insertProblem(){
        problemVariable = new problem__c(Name='problemVariable1');
        insert problemVariable;
    }
    public void displayProblem(){
        System.debug('problem - '+problemVariable);
    }

    public void insertPro(){
        proVariable = new pro__c(Name='pro1',problem__c=problemVariable.id,phone__c='9955663322');
        insert proVariable;
    }
    public void displayPro(){
        System.debug('pro - '+proVariable);
    }

}