src/objects/Applicant__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>Sri Lanka</fullName>
                </value>
                <value>
                    <fullName>Pakistan</fullName>
                </value>
                <value>
                    <fullName>Nepal</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <label>Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/applicantCombine.cls
public with sharing class applicantCombine {
    private final Applicant__c applicantVarible;

public applicantCombine(ApexPages.StandardController acon) {
    applicantVarible = [SELECT Id, Name, Address__c,Country__c,Zip_Code__c FROM Applicant__c
                WHERE Id = :ApexPages.currentPage().getParameters().get('id')];
}

public Map<String,String> getCombine(){
    Map<String,String> addressCombine = new Map<String, String>{'Address' => applicantVarible.Address__C, 
            'Country' => applicantVarible.Country__c};
    return addressCombine;
}

public String getCombineAddress(){
   return  applicantVarible.Address__C+','+applicantVarible.Country__c+','+applicantVarible.Zip_Code__c;
}

public Pagereference deleteApplicant(){
    delete applicantVarible;
    //Pagereference pageRef = new PageReference('Applicant__c/list?filterName=Recent');
   // pageRef.setRedirect(true);
    return new ApexPages.Action('{!List}').invoke();
   // return pageRef;
}
}