src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Mobile_Number__c</fullName>
        <label>Mobile Number</label>
        <type>Phone</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EmployeeExceptionExample.cls
public class EmployeeExceptionExample {
    public List<ID> sampleException(List<Employee__c> listEmployee){
        Database.SaveResult[] srList;
        List<ID> updatedID = new List<ID>{};
            for(Employee__c iterateVariable : listEmployee){
                if(iterateVariable.Name =='employeeName1'){ 
                    iterateVariable.Mobile_Number__c='';
                }else{
                    iterateVariable.Address__c='Mumbai';   
                }
            }
        try{
            srList = Database.update(listEmployee, true);  
            for(Database.SaveResult idVariable : srList){
                updatedID.add(idVariable.Id);
            }
        }catch(DmlException e){
            System.debug('The following exception has occurred: ' + e.getMessage());
        }
        return updatedID;
    }
}